export const SPORTS_BY_CATEGORY: Record<string, string[]> = {
  Force: ["Musculation", "Haltérophilie"],
  Endurance: [
    "Course à pied",
    "Cyclisme",
    "Natation",
    "Marche athlétique",
    "Athlétisme",
    "Course d'orientation",
    "Triathlon",
    "Vélo en salle",
  ],
  Collectif: [
    "Football",
    "Basketball",
    "Volleyball",
    "Beach-volley",
    "Handball",
    "Rugby",
    "Tennis",
    "Padel",
    "Badminton",
    "Squash",
    "Racquetball",
    "Hockey sur gazon",
    "Hockey sur glace",
    "Futsal",
    "Netball",
    "Lacrosse",
    "Cricket",
    "Baseball/softball",
    "Floorball",
    "Ultimate frisbee",
    "Water-polo",
  ],
  Combat: [
    "Boxe",
    "Kickboxing",
    "Karaté",
    "Taekwondo",
    "Judo",
    "Lutte",
    "MMA",
    "Kung-fu",
    "Kendo",
    "Escrime",
    "Arts martiaux frappés",
  ],
  Physique: ["CrossFit/HIIT/circuit training", "Calisthénie"],
  Nautique: [
    "Aviron",
    "Kayak/Canoë",
    "Stand-up paddle",
    "Surf",
    "Plongée",
    "Voile",
    "Windsurf/kitesurf",
    "Ski nautique/wakeboard",
  ],
  Hiver: ["Ski alpin", "Ski de fond", "Snowboard", "Patinage sur glace", "Raquettes"],
  Autre: [
    "Yoga",
    "Pilates",
    "Danse",
    "Zumba",
    "Randonnée",
    "Escalade",
    "Roller",
    "Golf",
    "Tennis de table",
    "Équitation",
    "Gymnastique",
    "Pétanque",
    "Skateboard",
    "Tir à l'arc",
    "Cheerleading",
  ],
};

export const INTENSITIES_BY_SPORT: Record<string, string[]> = {
  Musculation: ["moderee", "elevee", "tres_elevee"],
  "Course à pied": ["footing", "moderee", "soutenue", "rapide"],
  Cyclisme: ["loisir", "modere", "intense", "course"],
  Natation: ["loisir", "moderee", "intense"],
  Boxe: ["sac", "sparring", "round", "ring"],
  "CrossFit/HIIT/circuit training": ["modere", "intense"],
  Calisthénie: ["moderee", "intense"],
  Football: ["loisir", "competition"],
  Basketball: ["general", "match"],
  Volleyball: ["loisir", "competition"],
  Rugby: ["competition", "touch"],
  Tennis: ["modere", "simple", "double"],
  Padel: ["modere", "competition"],
  Badminton: ["loisir", "competition"],
  Racquetball: ["general", "competition"],
  "Hockey sur glace": ["general", "competition"],
  Karaté: ["novice", "modere"],
  Taekwondo: ["combat"],
  Kendo: ["modere", "intense", "tres_intense"],
  Aviron: ["modere", "competition"],
  "Kayak/Canoë": ["loisir", "modere", "competition"],
  Surf: ["general", "competition"],
  Voile: ["loisir", "competition"],
  "Windsurf/kitesurf": ["modere", "intense"],
  "Ski alpin": ["modere", "intense"],
  "Ski de fond": ["modere", "intense"],
  Snowboard: ["loisir", "intense"],
  "Patinage sur glace": ["general", "rapide"],
  Raquettes: ["modere", "intense"],
  Yoga: ["general", "power", "intense"],
  Randonnée: ["cross", "sac"],
  Escalade: ["voie", "bloc"],
  Équitation: ["marche", "trot", "galop"],
  Skateboard: ["loisir", "competition"],
  Athlétisme: ["lancers", "sauts", "haies"],
  "Arts martiaux frappés": ["novice", "modere"],
};

export function getAllSports(): string[] {
  return Object.values(SPORTS_BY_CATEGORY).flat().sort((a, b) => a.localeCompare(b, "fr"));
}
